set(_AMENT_PACKAGE_NAME "numsr_turtlebot")
set(numsr_turtlebot_VERSION "0.0.1")
set(numsr_turtlebot_MAINTAINER "Matthew Elwin <elwin@northwestern.edu>")
set(numsr_turtlebot_BUILD_DEPENDS "turtlebot3_msgs" "nuturtlebot_msgs")
set(numsr_turtlebot_BUILDTOOL_DEPENDS "ament_cmake")
set(numsr_turtlebot_BUILD_EXPORT_DEPENDS "turtlebot3_msgs" "nuturtlebot_msgs")
set(numsr_turtlebot_BUILDTOOL_EXPORT_DEPENDS )
set(numsr_turtlebot_EXEC_DEPENDS "turtlebot3_msgs" "nuturtlebot_msgs")
set(numsr_turtlebot_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(numsr_turtlebot_GROUP_DEPENDS )
set(numsr_turtlebot_MEMBER_OF_GROUPS )
set(numsr_turtlebot_DEPRECATED "")
set(numsr_turtlebot_EXPORT_TAGS)
list(APPEND numsr_turtlebot_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
