set(_AMENT_PACKAGE_NAME "nuturtlebot_msgs")
set(nuturtlebot_msgs_VERSION "0.0.2")
set(nuturtlebot_msgs_MAINTAINER "Matthew Elwin <elwin@northwestern.edu>")
set(nuturtlebot_msgs_BUILD_DEPENDS "rosidl_default_generators" "builtin_interfaces")
set(nuturtlebot_msgs_BUILDTOOL_DEPENDS "ament_cmake")
set(nuturtlebot_msgs_BUILD_EXPORT_DEPENDS "builtin_interfaces")
set(nuturtlebot_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(nuturtlebot_msgs_EXEC_DEPENDS "rosidl_default_runtime" "builtin_interfaces")
set(nuturtlebot_msgs_TEST_DEPENDS )
set(nuturtlebot_msgs_GROUP_DEPENDS )
set(nuturtlebot_msgs_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(nuturtlebot_msgs_DEPRECATED "")
set(nuturtlebot_msgs_EXPORT_TAGS)
list(APPEND nuturtlebot_msgs_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
